# Generated by Django 5.2.7 on 2025-10-02 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_icon_skill_level_remove_skill_proficiency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='type',
        ),
    ]
